spring:
  datasource:
    name: MySQL Connection
    url: jdbc:mysql://localhost:3306/employee_ms_db
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true