spring:
  application:
    name: Spring App
  profiles:
    active: dev
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    org:
      ehcache: DEBUG

jwt:
  secret: bWFsb1RlemFTaWZyYTEyMy4=
  validityInHours: 60
  refreshTokenValidityInHours: 120
